version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "local_postgres"
    ports:
      - "54320:5432"
    volumes:
      - local_postgres_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  local_postgres_dbdata: